[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl", "gcc"]

[phases.install]
cmds = ["cargo build --release"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/qr-api"

[variables]
RUST_VERSION = "1.88"
NIXPACKS_BUILD_CMD = "cargo build --release" 