[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl"]

[phases.install]
cmds = ["cargo build --release"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/qr-api" 