[build]
builder = "nixpacks"

[deploy]
startCommand = "cargo run"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
RUST_VERSION = "1.70" 